# Generated by Django 4.2.8 on 2023-12-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='captcha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=5)),
                ('image', models.ImageField(upload_to='data/captchas/')),
            ],
        ),
    ]
