# Generated by Django 4.2.8 on 2023-12-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='captcha',
            name='answered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='captcha',
            name='answer',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
